name: Test .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add .NET support
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Add MsBuild
      uses: microsoft/setup-msbuild@v1.1.3
    - name: Load dependencies
      run: dotnet restore DocuSign.MyAPI\DocuSign.MyAPI.sln
    - name: Build project
      run: dotnet build DocuSign.MyAPI\DocuSign.MyAPI.sln --no-restore
    - name: Run tests
      run: dotnet test DocuSign.MyAPI\DocuSign.MyAPI.sln --no-build --verbosity normal
